##version: '3.8'

services:
  api:
    build: .
    container_name: cmpe272_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # FastAPI service
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    # Automatically load environment variables from .env
    env_file:
      - .env
    # Optional: if you want hot reload in dev
    volumes:
      - .:/app
  postgres:
    image: postgres:15
    container_name: cmpe272_postgres
    environment:
      POSTGRES_USER: ali
      POSTGRES_PASSWORD: ali
      POSTGRES_DB: cmpe272db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ali"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cmpe272_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: